export type JobBenefit = string;

export interface Job {
  id: string;
  title: string;
  location: string;
  salaryMin: number;
  salaryMax: number;
  currency: string;
  category: string;
  description: string[];
  benefits: JobBenefit[];
  urgent?: boolean;
  featured?: boolean;
  imageQuery: string;
}

export const jobs: Job[] = [
  {
    id: "warehouse-worker",
    title: "Warehouse Worker",
    location: "Poland",
    salaryMin: 900,
    salaryMax: 1300,
    currency: "€",
    category: "Logistics",
    description: [
      "Packing and sorting goods",
      "Loading and unloading products",
      "Scanning and labeling items",
      "Maintaining warehouse cleanliness",
    ],
    benefits: [
      "Accommodation support",
      "Overtime available",
      "Medical insurance",
      "Legal work permit process",
      "Stable working hours",
      "Paid annual leave",
    ],
    featured: true,
    imageQuery: "warehouse worker poland",
  },
  {
    id: "factory-production-worker",
    title: "Factory Production Worker",
    location: "Poland",
    salaryMin: 1000,
    salaryMax: 1500,
    currency: "€",
    category: "Manufacturing",
    description: [
      "Operating production machines",
      "Packaging finished products",
      "Quality checking items",
      "Following factory safety rules",
    ],
    benefits: [
      "Free training provided",
      "Transport facility",
      "Long-term employment",
      "Insurance coverage",
      "Overtime opportunities",
      "Friendly work environment",
    ],
    urgent: true,
    imageQuery: "factory production worker",
  },
  {
    id: "food-packing-staff",
    title: "Food Packing Staff",
    location: "Poland",
    salaryMin: 950,
    salaryMax: 1250,
    currency: "€",
    category: "Food Industry",
    description: [
      "Packing food products",
      "Label checking and sealing",
      "Maintaining hygiene standards",
      "Working in temperature-controlled areas",
    ],
    benefits: [
      "Accommodation assistance",
      "Easy and simple work",
      "Weekly off days",
      "Extra shift bonuses",
      "Medical insurance",
      "Legal contract",
    ],
    imageQuery: "food packaging factory",
  },
  {
    id: "construction-helper",
    title: "Construction Helper",
    location: "Poland",
    salaryMin: 1200,
    salaryMax: 1800,
    currency: "€",
    category: "Construction",
    description: [
      "Assisting skilled workers",
      "Carrying construction materials",
      "Site cleaning and maintenance",
      "Basic support work on construction sites",
    ],
    benefits: [
      "Overtime pay",
      "Safety equipment provided",
      "Accommodation support",
      "High demand job",
      "Long-term contract",
      "Insurance included",
    ],
    urgent: true,
    imageQuery: "construction worker site",
  },
  {
    id: "hotel-housekeeping",
    title: "Hotel Housekeeping Staff",
    location: "Poland",
    salaryMin: 900,
    salaryMax: 1200,
    currency: "€",
    category: "Hospitality",
    description: [
      "Cleaning hotel rooms",
      "Changing bed sheets and towels",
      "Maintaining room hygiene",
      "Supporting hotel operations",
    ],
    benefits: [
      "Free meals during duty",
      "Friendly environment",
      "Paid holidays",
      "Accommodation support",
      "Medical insurance",
      "Stable working schedule",
    ],
    imageQuery: "hotel housekeeping staff",
  },
  {
    id: "cleaner-maintenance",
    title: "Cleaner / Maintenance Staff",
    location: "Poland",
    salaryMin: 850,
    salaryMax: 1100,
    currency: "€",
    category: "Maintenance",
    description: [
      "Cleaning offices and buildings",
      "Waste management",
      "Maintaining hygiene standards",
      "Supporting maintenance teams",
    ],
    benefits: [
      "Fixed duty hours",
      "Paid annual leave",
      "Accommodation assistance",
      "Visa processing support",
      "Insurance provided",
      "Safe working environment",
    ],
    imageQuery: "office cleaning maintenance",
  },
  {
    id: "restaurant-kitchen-helper",
    title: "Restaurant Kitchen Helper",
    location: "Poland",
    salaryMin: 1000,
    salaryMax: 1400,
    currency: "€",
    category: "Food & Beverage",
    description: [
      "Assisting chefs in the kitchen",
      "Washing and preparing ingredients",
      "Maintaining kitchen cleanliness",
      "Supporting food preparation",
    ],
    benefits: [
      "Free meals",
      "Tips opportunity",
      "Accommodation support",
      "Friendly workplace",
      "Career growth opportunities",
      "Medical insurance",
    ],
    imageQuery: "restaurant kitchen helper cooking",
  },
  {
    id: "delivery-driver",
    title: "Delivery Driver",
    location: "Poland",
    salaryMin: 1200,
    salaryMax: 2000,
    currency: "€",
    category: "Transport",
    description: [
      "Delivering goods safely",
      "Following delivery schedules",
      "Maintaining vehicle cleanliness",
      "Customer interaction and support",
    ],
    benefits: [
      "Fuel support",
      "Performance bonuses",
      "Flexible working hours",
      "Insurance coverage",
      "Stable monthly income",
      "Long-term opportunities",
    ],
    featured: true,
    imageQuery: "delivery driver van road",
  },
  {
    id: "welder-technician",
    title: "Welder / Skilled Technician",
    location: "Poland",
    salaryMin: 1500,
    salaryMax: 2500,
    currency: "€",
    category: "Engineering",
    description: [
      "Welding metal structures",
      "Operating technical equipment",
      "Reading technical drawings",
      "Quality inspection work",
    ],
    benefits: [
      "High overtime earnings",
      "Skilled worker demand",
      "Accommodation support",
      "Long-term contract",
      "Insurance included",
      "Career development opportunities",
    ],
    urgent: true,
    imageQuery: "welder welding metal industrial",
  },
  {
    id: "caregiver-elderly",
    title: "Caregiver / Elderly Care Assistant",
    location: "Poland",
    salaryMin: 1100,
    salaryMax: 1700,
    currency: "€",
    category: "Healthcare",
    description: [
      "Assisting elderly people in daily activities",
      "Providing basic care and support",
      "Maintaining hygiene and comfort",
      "Supporting medication reminders",
    ],
    benefits: [
      "Food and accommodation provided",
      "Stable work environment",
      "Paid leave",
      "Medical insurance",
      "Friendly workplace",
      "Legal employment contract",
    ],
    featured: true,
    imageQuery: "caregiver elderly care assistant",
  },
];

export const jobCategories = [
  "All",
  ...Array.from(new Set(jobs.map((j) => j.category))),
];
