export type JobBenefit = string;

export interface Job {
  id: string;
  title: string;
  location: string;
  salaryMin: number;
  salaryMax: number;
  currency: string;
  category: string;
  overview: string;
  description: string[];
  requirements: string[];
  benefits: JobBenefit[];
  contractType: string;
  workSchedule: string;
  experienceLevel: string;
  language: string;
  accommodation: string;
  urgent?: boolean;
  featured?: boolean;
  imageQuery: string;
}

export const jobs: Job[] = [
  {
    id: "warehouse-worker",
    title: "Warehouse Worker",
    location: "Poland",
    salaryMin: 900,
    salaryMax: 1300,
    currency: "€",
    category: "Logistics",
    overview:
      "Join a modern warehouse team handling picking, packing, and dispatch. This role suits candidates who are organized, punctual, and comfortable with repetitive tasks.",
    description: [
      "Packing and sorting goods",
      "Loading and unloading products",
      "Scanning and labeling items",
      "Maintaining warehouse cleanliness",
    ],
    requirements: [
      "Basic English helpful (not always required)",
      "Ability to stand and lift light/medium loads",
      "Willingness to work shifts (day/night as assigned)",
      "Good attention to detail and safety rules",
    ],
    benefits: [
      "Accommodation support",
      "Overtime available",
      "Medical insurance",
      "Legal work permit process",
      "Stable working hours",
      "Paid annual leave",
    ],
    contractType: "Employment contract",
    workSchedule: "Shift work (40–48 hrs/week)",
    experienceLevel: "No experience required",
    language: "Basic English (preferred)",
    accommodation: "Support available",
    featured: true,
    imageQuery: "warehouse worker poland",
  },
  {
    id: "factory-production-worker",
    title: "Factory Production Worker",
    location: "Poland",
    salaryMin: 1000,
    salaryMax: 1500,
    currency: "€",
    category: "Manufacturing",
    overview:
      "Work on a production line in a clean, well-organized factory. Duties include operating simple machines and ensuring consistent quality standards.",
    description: [
      "Operating production machines",
      "Packaging finished products",
      "Quality checking items",
      "Following factory safety rules",
    ],
    requirements: [
      "Comfortable with repetitive production tasks",
      "Basic safety mindset and willingness to learn",
      "Able to work rotating shifts",
      "Good hand-eye coordination",
    ],
    benefits: [
      "Free training provided",
      "Transport facility",
      "Long-term employment",
      "Insurance coverage",
      "Overtime opportunities",
      "Friendly work environment",
    ],
    contractType: "Employment contract",
    workSchedule: "Rotating shifts (40–48 hrs/week)",
    experienceLevel: "Entry level",
    language: "Basic English (preferred)",
    accommodation: "Assistance available",
    urgent: true,
    imageQuery: "factory production worker",
  },
  {
    id: "food-packing-staff",
    title: "Food Packing Staff",
    location: "Poland",
    salaryMin: 950,
    salaryMax: 1250,
    currency: "€",
    category: "Food Industry",
    overview:
      "Pack and label food products while following hygiene and quality procedures. Suitable for candidates who can work carefully in a fast-paced environment.",
    description: [
      "Packing food products",
      "Label checking and sealing",
      "Maintaining hygiene standards",
      "Working in temperature-controlled areas",
    ],
    requirements: [
      "Willingness to follow strict hygiene rules",
      "Comfortable working in cooler environments when needed",
      "Ability to work on a line with speed and accuracy",
      "Teamwork and punctuality",
    ],
    benefits: [
      "Accommodation assistance",
      "Easy and simple work",
      "Weekly off days",
      "Extra shift bonuses",
      "Medical insurance",
      "Legal contract",
    ],
    contractType: "Employment contract",
    workSchedule: "Shift work (40–48 hrs/week)",
    experienceLevel: "No experience required",
    language: "Basic English (preferred)",
    accommodation: "Assistance available",
    imageQuery: "food packaging factory",
  },
  {
    id: "construction-helper",
    title: "Construction Helper",
    location: "Poland",
    salaryMin: 1200,
    salaryMax: 1800,
    currency: "€",
    category: "Construction",
    overview:
      "Support skilled workers on active construction sites. This role is physical and hands-on, ideal for candidates who are fit and safety-focused.",
    description: [
      "Assisting skilled workers",
      "Carrying construction materials",
      "Site cleaning and maintenance",
      "Basic support work on construction sites",
    ],
    requirements: [
      "Physically fit and comfortable with outdoor work",
      "Willingness to follow safety instructions",
      "Basic construction experience is a plus (not required)",
      "Reliable attendance and teamwork",
    ],
    benefits: [
      "Overtime pay",
      "Safety equipment provided",
      "Accommodation support",
      "High demand job",
      "Long-term contract",
      "Insurance included",
    ],
    contractType: "Employment contract",
    workSchedule: "Day shift (40–48 hrs/week)",
    experienceLevel: "Entry level (experience helps)",
    language: "Basic English (preferred)",
    accommodation: "Support available",
    urgent: true,
    imageQuery: "construction worker site",
  },
  {
    id: "hotel-housekeeping",
    title: "Hotel Housekeeping Staff",
    location: "Poland",
    salaryMin: 900,
    salaryMax: 1200,
    currency: "€",
    category: "Hospitality",
    overview:
      "Maintain cleanliness and comfort standards in hotel rooms and common areas. Ideal for detail-oriented candidates who enjoy structured work.",
    description: [
      "Cleaning hotel rooms",
      "Changing bed sheets and towels",
      "Maintaining room hygiene",
      "Supporting hotel operations",
    ],
    requirements: [
      "Attention to detail and cleanliness",
      "Ability to work on your feet for long periods",
      "Positive attitude and guest-friendly behavior",
      "Prior housekeeping experience is a plus",
    ],
    benefits: [
      "Free meals during duty",
      "Friendly environment",
      "Paid holidays",
      "Accommodation support",
      "Medical insurance",
      "Stable working schedule",
    ],
    contractType: "Employment contract",
    workSchedule: "Day shift / split shift (40–48 hrs/week)",
    experienceLevel: "Entry level (experience helps)",
    language: "Basic English (preferred)",
    accommodation: "Support available",
    imageQuery: "hotel housekeeping staff",
  },
  {
    id: "cleaner-maintenance",
    title: "Cleaner / Maintenance Staff",
    location: "Poland",
    salaryMin: 850,
    salaryMax: 1100,
    currency: "€",
    category: "Maintenance",
    overview:
      "Keep offices and facilities clean, safe, and well-maintained. Best for candidates who are dependable and comfortable with routine cleaning tasks.",
    description: [
      "Cleaning offices and buildings",
      "Waste management",
      "Maintaining hygiene standards",
      "Supporting maintenance teams",
    ],
    requirements: [
      "Basic cleaning experience helpful (not required)",
      "Responsible and able to follow checklists",
      "Comfortable using standard cleaning tools",
      "Teamwork and punctuality",
    ],
    benefits: [
      "Fixed duty hours",
      "Paid annual leave",
      "Accommodation assistance",
      "Visa processing support",
      "Insurance provided",
      "Safe working environment",
    ],
    contractType: "Employment contract",
    workSchedule: "Fixed hours (40–48 hrs/week)",
    experienceLevel: "No experience required",
    language: "Basic English (preferred)",
    accommodation: "Assistance available",
    imageQuery: "office cleaning maintenance",
  },
  {
    id: "restaurant-kitchen-helper",
    title: "Restaurant Kitchen Helper",
    location: "Poland",
    salaryMin: 1000,
    salaryMax: 1400,
    currency: "€",
    category: "Food & Beverage",
    overview:
      "Support the kitchen team with prep, cleaning, and basic food handling. Great for candidates who enjoy teamwork in a fast-paced environment.",
    description: [
      "Assisting chefs in the kitchen",
      "Washing and preparing ingredients",
      "Maintaining kitchen cleanliness",
      "Supporting food preparation",
    ],
    requirements: [
      "Willingness to follow hygiene and safety rules",
      "Able to work during peak hours/weekends",
      "Quick learner and team player",
      "Kitchen experience is a plus (not required)",
    ],
    benefits: [
      "Free meals",
      "Tips opportunity",
      "Accommodation support",
      "Friendly workplace",
      "Career growth opportunities",
      "Medical insurance",
    ],
    contractType: "Employment contract",
    workSchedule: "Shift work (40–48 hrs/week)",
    experienceLevel: "Entry level",
    language: "Basic English (preferred)",
    accommodation: "Support available",
    imageQuery: "restaurant kitchen helper cooking",
  },
  {
    id: "delivery-driver",
    title: "Delivery Driver",
    location: "Poland",
    salaryMin: 1200,
    salaryMax: 2000,
    currency: "€",
    category: "Transport",
    overview:
      "Deliver packages safely and on time across assigned routes. Ideal for responsible drivers who can follow schedules and provide good customer service.",
    description: [
      "Delivering goods safely",
      "Following delivery schedules",
      "Maintaining vehicle cleanliness",
      "Customer interaction and support",
    ],
    requirements: [
      "Valid driving license (category depends on role)",
      "Safe driving habits and punctuality",
      "Basic navigation skills (GPS/maps)",
      "Customer-friendly communication",
    ],
    benefits: [
      "Fuel support",
      "Performance bonuses",
      "Flexible working hours",
      "Insurance coverage",
      "Stable monthly income",
      "Long-term opportunities",
    ],
    contractType: "Employment contract",
    workSchedule: "Flexible / shifts (40–50 hrs/week)",
    experienceLevel: "Some driving experience preferred",
    language: "Basic English (preferred)",
    accommodation: "Assistance available",
    featured: true,
    imageQuery: "delivery driver van road",
  },
  {
    id: "welder-technician",
    title: "Welder / Skilled Technician",
    location: "Poland",
    salaryMin: 1500,
    salaryMax: 2500,
    currency: "€",
    category: "Engineering",
    overview:
      "Perform welding and technical fabrication work based on drawings and specifications. This role fits skilled candidates who can maintain high quality standards.",
    description: [
      "Welding metal structures",
      "Operating technical equipment",
      "Reading technical drawings",
      "Quality inspection work",
    ],
    requirements: [
      "Relevant welding/technical experience",
      "Ability to read basic technical drawings",
      "Focus on quality and safety",
      "Certificates are a plus (if available)",
    ],
    benefits: [
      "High overtime earnings",
      "Skilled worker demand",
      "Accommodation support",
      "Long-term contract",
      "Insurance included",
      "Career development opportunities",
    ],
    contractType: "Employment contract",
    workSchedule: "Shift work (40–50 hrs/week)",
    experienceLevel: "Skilled",
    language: "Basic English (preferred)",
    accommodation: "Support available",
    urgent: true,
    imageQuery: "welder welding metal industrial",
  },
  {
    id: "caregiver-elderly",
    title: "Caregiver / Elderly Care Assistant",
    location: "Poland",
    salaryMin: 1100,
    salaryMax: 1700,
    currency: "€",
    category: "Healthcare",
    overview:
      "Assist elderly clients with daily activities and basic care under a structured routine. Best for empathetic candidates with a caring attitude.",
    description: [
      "Assisting elderly people in daily activities",
      "Providing basic care and support",
      "Maintaining hygiene and comfort",
      "Supporting medication reminders",
    ],
    requirements: [
      "Caring attitude and patience",
      "Basic caregiving experience helpful (not required)",
      "Willingness to follow routines and instructions",
      "Comfortable assisting with mobility and daily tasks",
    ],
    benefits: [
      "Food and accommodation provided",
      "Stable work environment",
      "Paid leave",
      "Medical insurance",
      "Friendly workplace",
      "Legal employment contract",
    ],
    contractType: "Employment contract",
    workSchedule: "Shift work (40–48 hrs/week)",
    experienceLevel: "Entry level (experience helps)",
    language: "Basic English (preferred)",
    accommodation: "Provided / support available",
    featured: true,
    imageQuery: "caregiver elderly care assistant",
  },
  {
    id: "agricultural-greenhouse-worker",
    title: "Agricultural Greenhouse Worker",
    location: "Poland",
    salaryMin: 950,
    salaryMax: 1350,
    currency: "€",
    category: "Agriculture",
    overview:
      "Work in modern, temperature-controlled greenhouse complexes planting, cultivating, and harvesting fruits, vegetables, or flowers. Ideal for individuals who enjoy practical, active work.",
    description: [
      "Harvesting and sorting fresh produce",
      "Planting seedlings and trimming vines",
      "Packing and prepping items for shipment",
      "Monitoring automated watering setups",
    ],
    requirements: [
      "Good physical stamina and manual dexterity",
      "Ability to handle warm greenhouse environments",
      "Willingness to learn agricultural protocols",
      "Punctuality and strong team cooperation",
    ],
    benefits: [
      "Subsidized housing provided",
      "Seasonal performance bonuses",
      "Free fresh vegetables/produce allowances",
      "Full medical coverage and legal permit",
      "Consistent shift hours with optional overtime",
    ],
    contractType: "Employment contract",
    workSchedule: "Day shifts (40–48 hrs/week)",
    experienceLevel: "No experience required",
    language: "Basic English (preferred)",
    accommodation: "Provided / support available",
    imageQuery: "modern greenhouse agriculture worker",
  },
  {
    id: "forklift-operator-logistics",
    title: "Forklift Operator / Logistics Specialist",
    location: "Poland",
    salaryMin: 1300,
    salaryMax: 1900,
    currency: "€",
    category: "Logistics",
    overview:
      "Safely operate forklift machinery to move, stack, and organize industrial pallets within major distribution hubs. Best suited for attentive individuals with mechanical awareness.",
    description: [
      "Operating high-reach UDT-certified forklifts",
      "Loading or unloading shipping containers",
      "Verifying stock locations using RF scanners",
      "Complying with tight safety zone protocols",
    ],
    requirements: [
      "Prior forklift experience or local machine pass",
      "Strong spatial awareness and safety emphasis",
      "Willingness to handle high-demand shift rosters",
      "Basic inventory tracking literacy",
    ],
    benefits: [
      "UDT certification training sponsorship",
      "High overtime premium rates",
      "Subsidized company accommodation",
      "Comprehensive workplace accident insurance",
      "Long-term career progression routes",
    ],
    contractType: "Employment contract",
    workSchedule: "Rotating shifts (40–50 hrs/week)",
    experienceLevel: "Experience preferred",
    language: "Basic English (preferred)",
    accommodation: "Support available",
    urgent: true,
    imageQuery: "forklift driver industrial warehouse",
  },
  {
    id: "textile-sewing-machinist",
    title: "Industrial Textile Sewing Machinist",
    location: "Poland",
    salaryMin: 1100,
    salaryMax: 1600,
    currency: "€",
    category: "Manufacturing",
    overview:
      "Operate professional automated sewing equipment in clean, fast-paced textile assembly facilities producing commercial apparel, upholstery, or interiors.",
    description: [
      "Stitching fabric panels per design layouts",
      "Configuring industrial sewing machinery lines",
      "Performing regular inline material quality checks",
      "Organizing work batches systematically",
    ],
    requirements: [
      "Basic competence with sewing gear or tailors",
      "Excellent hand-eye coordination and fine focus",
      "Patience for detail-driven, repeatable metrics",
      "Reliable attendance habits",
    ],
    benefits: [
      "Piece-rate production speed bonuses",
      "Modern, well-lit workspace setup",
      "Full residency visa administrative support",
      "Paid onboarding familiarization phase",
      "Standard health and pension insurance",
    ],
    contractType: "Employment contract",
    workSchedule: "Day shifts (40–45 hrs/week)",
    experienceLevel: "Entry level (experience helps)",
    language: "Basic English (preferred)",
    accommodation: "Assistance available",
    featured: true,
    imageQuery: "industrial sewing machine factory",
  },
  {
    id: "electronic-assembly-operator",
    title: "Electronic Component Assembly Operator",
    location: "Poland",
    salaryMin: 1050,
    salaryMax: 1450,
    currency: "€",
    category: "Electronics",
    overview:
      "Assemble, test, and package complex micro-components or home appliances along high-tech automated lines. Great for individuals who prefer dust-free, climate-controlled tech environments.",
    description: [
      "Mounting small electronic parts onto panels",
      "Running routine diagnostic test systems",
      "Visual defect inspection under loupes/scopes",
      "Packing ready systems into secure consumer boxes",
    ],
    requirements: [
      "Strong close-range eyesight and finger precision",
      "Ability to safely use handheld precision tools",
      "Strict compliance with anti-static (ESD) safety",
      "Capacity for structured, sitting or standing tasks",
    ],
    benefits: [
      "Air-conditioned, modern tech factory floor",
      "Attendance consistency payroll bonuses",
      "Subsidized hot canteen lunches daily",
      "State health card and legal paperwork setup",
      "Regular night shift allowance premium rates",
    ],
    contractType: "Employment contract",
    workSchedule: "Three-shift system (40–48 hrs/week)",
    experienceLevel: "No experience required",
    language: "Basic English (preferred)",
    accommodation: "Support available",
    imageQuery: "electronics microchip factory assembly",
  },
  {
    id: "laundry-facility-operator",
    title: "Commercial Laundry Facility Operator",
    location: "Poland",
    salaryMin: 900,
    salaryMax: 1250,
    currency: "€",
    category: "Hospitality",
    overview:
      "Process high-volume industrial linen, towels, and uniforms serving major hospitality chains and hospitals. Excellent for individuals looking for simple, fast-paced team roles.",
    description: [
      "Loading commercial washing and drying machines",
      "Feeding sheets into automated rolling irons",
      "Folding, bundling, and wrapping finished items",
      "Sorting inbound textiles by type and stain level",
    ],
    requirements: [
      "Ability to manage physical routines and standing",
      "Comfort working around steam/warm surroundings",
      "High pacing accuracy during busy processing cycles",
      "Strong reliability and timekeeping focus",
    ],
    benefits: [
      "Free uniform sets and safety apparel",
      "Predictable, structured shift timetables",
      "Legal work permit and full medical file",
      "Affordable shared worker housing arrangements",
      "Extra shifts available for fast tracking pay",
    ],
    contractType: "Employment contract",
    workSchedule: "Two-shift system (40–48 hrs/week)",
    experienceLevel: "No experience required",
    language: "Basic English (preferred)",
    accommodation: "Assistance available",
    urgent: true,
    imageQuery: "commercial laundry factory machine",
  },
  {
    id: "it-software-engineer",
    title: "IT Software Engineer",
    location: "Poland (Hybrid/Remote)",
    salaryMin: 2000,
    salaryMax: 3500,
    currency: "€",
    category: "IT",
    overview:
      "Develop, maintain, and scale modern web applications and internal API services. Work closely with cross-functional teams to deliver clean, production-ready features.",
    description: [
      "Developing frontend and backend web application features",
      "Writing clean, maintainable, and type-safe code architectures",
      "Integrating relational databases and managing data workflows",
      "Debugging performance bottlenecks and optimizing core queries",
    ],
    requirements: [
      "Solid understanding of JavaScript/TypeScript and web ecosystems",
      "Familiarity with modern framework patterns and database tools",
      "Basic understanding of Git workflows and version control",
      "Good team communication and technical problem-solving ability",
    ],
    benefits: [
      "B2B or UoP contract flexibility",
      "Private healthcare package (Medicover/Luxmed)",
      "Co-financed sports card (Multisport)",
      "Remote work stipend or modern office desk space",
      "Budget for professional certifications and courses",
      "Paid integration events",
    ],
    contractType: "Employment / B2B contract",
    workSchedule: "Flexible hours (40 hrs/week)",
    experienceLevel: "Junior / Mid-level",
    language: "English (Required)",
    accommodation: "Relocation/Support available",
    featured: true,
    imageQuery: "software engineer working on code editor desk",
  },
  {
    id: "ai-ml-engineer",
    title: "AI / Machine Learning Engineer",
    location: "Poland (Hybrid/Remote)",
    salaryMin: 2300,
    salaryMax: 4200,
    currency: "€",
    category: "IT",
    overview:
      "Implement, fine-tune, and deploy predictive models and generative AI systems. Bridges the gap between prototype machine learning algorithms and robust production infrastructure.",
    description: [
      "Building and evaluating deep learning or generative architectures",
      "Creating pipeline tasks for processing or cleaning large datasets",
      "Deploying model endpoints into secure cloud environments",
      "Optimizing token contexts or model performance latencies",
    ],
    requirements: [
      "Strong proficiency in Python and basic data libraries",
      "Exposure to training frameworks or modern model APIs",
      "Understanding of REST APIs and server-side deployment setups",
      "Analytical mindset with strong mathematical fundamentals",
    ],
    benefits: [
      "High-end hardware budget (M-series Mac or GPU cloud access)",
      "B2B tax optimization schemes (IP-Box support options)",
      "Premium medical and mental health cover",
      "Flexible hybrid working models across major tech hubs",
      "Sponsorship for global AI and tech conferences",
    ],
    contractType: "Employment / B2B contract",
    workSchedule: "Flexible hours (40 hrs/week)",
    experienceLevel: "Entry-level / Mid-level",
    language: "English (Required)",
    accommodation: "Relocation/Support available",
    urgent: true,
    imageQuery:
      "data scientist analyzing machine learning algorithms on monitor",
  },
];

export const jobCategories = [
  "All",
  ...Array.from(new Set(jobs.map((j) => j.category))),
];
